import boto3
import time
import yaml
refactor_space_client = boto3.client('migration-hub-refactor-spaces')

def delete_flux_service(envId,appId,name):

    print ('delete_flux_service')

    seevicelist_response = refactor_space_client.list_services(
        ApplicationIdentifier=appId,
        EnvironmentIdentifier=envId,
        MaxResults=100
    )
    print (seevicelist_response)

    routelist_response = refactor_space_client.list_routes(
        ApplicationIdentifier=appId,
        EnvironmentIdentifier=envId,
        MaxResults=100
    )

    print (routelist_response)
    
    ServiceSummaryList = seevicelist_response["ServiceSummaryList"]
    RouteSummaryList = routelist_response["RouteSummaryList"]

    print ("ServiceSummaryList")
    print (ServiceSummaryList)
    print ("RouteSummaryList")
    print (RouteSummaryList)

    routeDeletion = False
    # delete the routes
    for s in ServiceSummaryList:
        if s["Name"]==name:
            print ("Match Found:::: "+s["Name"]+" is "+name)
            for r in routelist_response["RouteSummaryList"]:
                   if r["ServiceId"] == s["ServiceId"]:
                        print(name+" - deleting route "+r["RouteId"])
                        refactor_space_client.delete_route(
                            ApplicationIdentifier=appId,
                            EnvironmentIdentifier=envId,
                            RouteIdentifier=r["RouteId"]
                        )
                        routeDeletion = True
    if routeDeletion : time.sleep(60) #wait for 60 sec

    for s in seevicelist_response["ServiceSummaryList"]:
        if s["Name"]==name:
            print(name+" - deleting service")
            refactor_space_client.delete_service(
                ApplicationIdentifier=appId,
                EnvironmentIdentifier=envId,
                ServiceIdentifier=s["ServiceId"]
            )

def create_flux_service(envId,appId,vpcId,name,url,healthCheckUrl, path, method):

    print ("inside create_flux_service")
    print ("url:"+url)
    print ("healthCheckUrl:"+healthCheckUrl)
    print ("path:"+path)
    print ("method:"+method)

    # delete the service and routes if exists
    delete_flux_service(envId,appId,name)


    response = refactor_space_client.create_service(
        ApplicationIdentifier=appId,
        Description='Autogenerated service created by refactor-space-eks-controller',
        EndpointType="URL",
        EnvironmentIdentifier=envId,
        Name=name,
        UrlEndpoint={
            'HealthUrl': healthCheckUrl,
            'Url': url
        },
        VpcId=vpcId
    )
    print(name+' service created: '+ response['ServiceId'])

    time.sleep(10) #wait for 10 sec

    print(name+' now creating route: for '+ path +" with "+method)


    print("appId:"+appId)
    print("envId:"+envId)
    print("RouteType='URI_PATH'")
    print("ServiceIdentifier:"+response['ServiceId'])
    print("Methods:"+method)
    print("SourcePath:"+path)


    route_response = refactor_space_client.create_route(
        ApplicationIdentifier=appId,
        EnvironmentIdentifier=envId,
        RouteType='URI_PATH',
        ServiceIdentifier=response['ServiceId'],
        UriPathRoute={
            'ActivationState': 'ACTIVE',
            'IncludeChildPaths': True,
            'Methods': [ 
                method,
            ],
            'SourcePath': path
        }
    )

    return response['ServiceId']

